name: package-with-csv-resource
resources:
  - name: r-table-reverse-csv
    path: data/table-reverse.csv
    schema:
      fields:
        - name: id
          type: integer
        - name: name
          type: string
