name: package-with-csv-resource
resources:
  - name: number-two
    path: table-reverse.csv
    schema:
      fields:
        - name: id
          type: integer
        - name: name
          type: string
